services:
  - type: web
    name: video-management
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y
      pip install --no-cache-dir -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PIP_NO_CACHE_DIR
        value: "false"
    plan: free
    numInstances: 1
